const FIELD_ID = '#secure-payment-field';

export const style = {
  input: {
    outline: '0',
    'font-family': 'Poppins, sans-serif',
    width: '100% !important',
  },
  [`${FIELD_ID}`]: {
    'font-family': 'Poppins, sans-serif',
    'box-sizing': 'border-box',
    display: 'block',
    height: '3rem',
    border: '1px solid rgba(255, 255, 255, 0.40)',
    background: 'rgba(255, 255, 255, 0.03)',
    padding: '0.84rem 0.75rem',
    color: '#FFF',
    'font-size': '0.875rem',
    'font-style': 'normal',
    'font-weight': 500,
    'line-height': 'normal',
    width: '100%',
  },
  [`${FIELD_ID}[name=submit]:active`]: {
    background: 'linear-gradient(180deg, #FFB800 0%, #E97000 100%)',
    'box-shadow': '0px 4px 16px 0px rgba(0, 0, 0, 0.15)',
    color: '#FFF',
    'text-shadow': '0px 1px 3px rgba(0, 0, 0, 0.25)',
    'font-size': '1rem',
    'font-weight': '700',
    'line-height': 'normal',
    'text-transform': 'uppercase',
    'font-family': 'Poppins, sans-serif',
    border: 'none',
  },
  [`${FIELD_ID}.submit:active`]: {
    color: '#ffffff',
    background: 'linear-gradient(180deg, #E5A500 0%, #D16500 100%) !important',
    'box-shadow': '0px 4px 16px 0px rgba(0, 0, 0, 0.15)',
    outline: 'none',
    border: 'none !important',
  },
  [`${FIELD_ID}.submit:focus`]: { outline: 'none', border: 'none !important' },
  [`${FIELD_ID}.submit:hover`]: {
    background: 'linear-gradient(180deg, #FFC533 0%, #ED8D33 100%)',
  },
  '#heartland-field-wrapper #heartland-field:focus': {
    border: '1px solid var(--Primary, #E98C00)',
    outline: 'none',
  },
  [`${FIELD_ID}.submit`]: {
    'box-sizing': 'border-box',
    display: 'flex',
    width: '22.5rem',
    height: '3.125rem !important',
    padding: '0.6875rem 1rem',
    'justify-content': 'center',
    'align-items': 'center',
    'text-align': 'center',
    'white-space': 'nowrap',
    'vertical-align': 'middle',
    '-ms-touch-action': 'manipulation',
    'touch-action': 'manipulation',
    cursor: 'pointer',
    '-webkit-user-select': 'none',
    '-moz-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
    'background-image': 'none',
    background: 'linear-gradient(180deg, #FFB800 0%, #E97000 100%)',
    'box-shadow': '0px 4px 16px 0px rgba(0, 0, 0, 0.15)',
    color: '#FFF',
    'text-shadow': '0px 1px 3px rgba(0, 0, 0, 0.25)',
    'font-size': '1rem',
    'font-weight': '700',
    'line-height': 'normal',
    'text-transform': 'uppercase',
    'font-family': 'Poppins, sans-serif',
  },

  [`${FIELD_ID}::-webkit-input-placeholder`]: {
    color: 'rgba(255, 255, 255, 0.60)',
    'font-size': '0.875rem',
    'font-weight': 500,
    'line-height': 'normal',
    'font-family': 'Poppins, sans-serif',
  },
  [`${FIELD_ID}::-moz-placeholder`]: {
    color: 'rgba(255, 255, 255, 0.60)',
    'font-size': '0.875rem',
    'font-weight': 500,
    'line-height': 'normal',
    'font-family': 'Poppins, sans-serif',
  },
  [`${FIELD_ID}:-ms-input-placeholder`]: {
    color: 'rgba(255, 255, 255, 0.60)',
    'font-size': '0.875rem',
    'font-weight': 500,
    'line-height': 'normal',
    'font-family': 'Poppins, sans-serif',
  },
  [`${FIELD_ID}:-moz-placeholder`]: {
    color: 'rgba(255, 255, 255, 0.60)',
    'font-size': '0.875rem',
    'font-weight': 500,
    'line-height': 'normal',
    'font-family': 'Poppins, sans-serif',
  },

  [`input${FIELD_ID}[name=cardNumber]::-ms-clear`]: {
    display: 'none',
  },
};
