export const terms = `<p>The Terms and Conditions, hereinafter referred to together as the &ldquo;Contract&rdquo; or &ldquo;Agreement&ldquo; is made by and between Elite Fleet Group LLC, 66 W Flagler Street STE 900 Miami, FL 33130, United States hereinafter referred to as &ldquo;Owner", and renter hereinafter referred to as "Renter&rdquo; (each a &ldquo;Party&rdquo; and together the &ldquo;Parties&rdquo;) relating to the rental of vehicle hereinafter referred to as &ldquo;Vehicle&rdquo;.</p>
<p>Vehicle:<br/>The Owner hereby rents to Renter the vehicle described in the Contract hereinafter referred to as &ldquo;Vehicle&rdquo; upon the conditions and covenants set in the Contract.</p>
<p>Rental Period:<br/>Owner agrees to rent Vehicle to Renter for the period set in the Contract. The Parties agree that the Agreement terminates upon the end date specified in the Contract. If the Agreement is terminated prior to the end date, the Parties will work together to determine whether a refund of rental fees is necessary, and the parties shall have no further liability to one other.</p>
<p>Renter Obligations:<br/>The Renter will assume all risk of loss and damage to the Vehicle. The Agreement does not include physical damage of liability insurance for bodily injury or property damage cause to others.<br/>The Renter agrees to indemnify the Owner from any loss, and in order to prevent such loss, the Renter will do the following:</p>
<ol>
<li>Keep the Vehicle free of encumbrances, such as fines and liens.</li>
<li>Indemnify the Owner from all insurance claims and expenses resulting from the maintenance and use of the Vehicle; and</li>
<li>Pay all amounts owned under the Agreement without deducting any amounts the Renter claims to be owed by the Owner.</li>
</ol>
<p>The Renter agrees to co-operate with Owner and the Insurance Company in pursuing or defending any claim or action resulting from the use of the Vehicle. Any award of money the Renter receives as a result of a claim or action is to be assigned to the Owner. If the Renter fails to maintain insurance or if a claim is denied by the Owner&rsquo;s insurance company for any reason, the Renter remains responsible to pay the total cost of the Rental Vehicle.</p>
<p>Excessive Wear and Tear:<br/>The Renter is responsible for ensuring that the Vehicle is regularly maintained and is kept in good repair. Regular maintenance includes but is not limited to the excessive wear and tear provisions below. The Renter is to pay the costs of regular maintenance and any costs for repairs not covered by warranty.<br/>Excessive wear and tear will include, but is not limited to, the following:</p>
<ol>
<li>cracked, damaged, or tinted glass;</li>
<li>dented or damaged body panels, fenders, lights or paint;</li>
<li>missing equipment or accessories that were provided with the Vehicle, including but not limited to spare tire or regular tires;</li>
<li>damage to the interior of the Vehicle, including but not limited to the dash, seats, floor covering, upholster, or;</li>
<li>mechanical damage that affects the safe, proper, or lawful operation of the Vehicle, which would include damage that causes the Vehicle to fail a safety inspection in the state of New York where this agreement is signed.</li>
</ol>
<p>Mileage Limit:<br/>Renter will obey the mileage limit for the vehicle specified in the Contract.</p>
<p>Limit Deposit:<br/>The renter agrees to make a deposit of $1,000 with the Owner, said deposit to be used, in the event of loss of or damage to the Vehicle or equipment during the term of this Car Rental Agreement, to defray fully or partially the cost of necessary repairs or replacement. In the absence of damage or loss, said deposit shall be credited toward payment of the Rental Rate and excess shall be returned to the Renter.</p>
<p>Payment:<br/>The full payment is due on the start date specified in the Contract. $1,000 is the refundable deposit. All payments must be transferred to Owner directly.</p>
<p>Rental Vehicle: <br/>The vehicle shall be operated by the Renter to serve the best interest and welfare of the Owner and the public. The vehicle shall be maintained and operated in a manner that will provide the maximum amount of safety and protection to the Renter&rsquo;s passengers. The Renter shall adhere to all drivers&rsquo; license requirements set forth by the State of Florida and Federal Governments. The Renter shall not sublease the Owner&rsquo;s vehicle to another entity without the expressed written consent of the Owner. The Renter shall not alter or modify the vehicle without the expressed written consent of the Owner.</p>`;
